apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://{{ include "e-team.prometheusName" . }}:{{ .Values.observability.prometheus.service.port }}
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://{{ include "e-team.lokiName" . }}:{{ .Values.observability.loki.service.port }}
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://{{ include "e-team.tempoName" . }}:{{ .Values.observability.tempo.service.port }}
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
      serviceMap:
        datasourceUid: prometheus
