auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2026-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        # index_2024-04-22 
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
  aws:
    bucketnames: ${S3_BUCKET}
    region: ${AWS_REGION}
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}

limits_config:
  # enable log to contain key-value metadata e.g. Otel log attributes
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 672h # 28 days retention

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: s3

analytics:
  # not report data used to Grafana
  reporting_enabled: false
