#!/usr/bin/env ruby
# frozen_string_literal: true

# Reads charts/e-team/values.yaml and writes compose.values.env for Docker Compose.
# Run from repo root: ruby scripts/gen-compose-env-from-values.rb

require "yaml"

ROOT = File.expand_path("..", __dir__)
VALUES_PATH = File.join(ROOT, "charts/e-team/values.yaml")
OUT_PATH = ARGV[0] ? File.expand_path(ARGV[0]) : File.join(ROOT, "compose.values.env")

def image_string(h)
  raise ArgumentError, "missing image hash" unless h.is_a?(Hash)

  "#{h.fetch('repository')}:#{h.fetch('tag')}"
end

v = YAML.load_file(VALUES_PATH)
obs = v["observability"] || {}

lines = []
lines << "# Generated by scripts/gen-compose-env-from-values.rb from charts/e-team/values.yaml"
lines << "# DO NOT EDIT BY HAND — run: ruby scripts/gen-compose-env-from-values.rb"

lines << "POSTGRES_USER=#{v.dig('postgres', 'auth', 'username')}"
lines << "POSTGRES_PASSWORD=#{v.dig('postgres', 'auth', 'password')}"
lines << "POSTGRES_DB=#{v.dig('postgres', 'auth', 'database')}"

lines << "POSTGRES_IMAGE=#{image_string(v.dig('postgres', 'image'))}"
lines << "MIGRATION_IMAGE=#{image_string(v.dig('migration', 'image'))}"

lines << "API_GATEWAY_IMAGE=#{image_string(v.dig('apiGateway', 'image'))}"
lines << "VALIDATION_SERVICE_IMAGE=#{image_string(v.dig('validationService', 'image'))}"
lines << "EXECUTION_SERVICE_IMAGE=#{image_string(v.dig('executionService', 'image'))}"
lines << "WORKER_SERVICE_IMAGE=#{image_string(v.dig('workerService', 'image'))}"
lines << "REPORTING_SERVICE_IMAGE=#{image_string(v.dig('reportingService', 'image'))}"

lines << "PROMETHEUS_IMAGE=#{image_string(obs.dig('prometheus', 'image'))}"
lines << "LOKI_IMAGE=#{image_string(obs.dig('loki', 'image'))}"
lines << "TEMPO_IMAGE=#{image_string(obs.dig('tempo', 'image'))}"
lines << "OTEL_COLLECTOR_IMAGE=#{image_string(obs.dig('otelCollector', 'image'))}"
lines << "PROMTAIL_IMAGE=#{image_string(obs.dig('promtail', 'image'))}"
lines << "GRAFANA_IMAGE=#{image_string(obs.dig('grafana', 'image'))}"

rabbit = v.dig("composeLocal", "rabbitmq", "image") || "rabbitmq:3-management-alpine"
lines << "RABBITMQ_IMAGE=#{rabbit}"

File.write(OUT_PATH, lines.join("\n") + "\n")
puts "Wrote #{OUT_PATH}" if ARGV.empty?
