#!/usr/bin/env ruby
# frozen_string_literal: true

# Reads charts/cicd/values.yaml and writes compose.values.env for Docker Compose.
# Single source of truth with Helm: images, ports, service URLs, DB DSN, RabbitMQ auth/URL, OTel endpoint/protocol.
# Run from repo root: ruby scripts/gen-compose-env-from-values.rb

require "uri"
require "yaml"

ROOT = File.expand_path("..", __dir__)
VALUES_PATH = File.join(ROOT, "charts/cicd/values.yaml")
OUT_PATH = ARGV[0] ? File.expand_path(ARGV[0]) : File.join(ROOT, "compose.values.env")

def image_string(h)
  raise ArgumentError, "missing image hash" unless h.is_a?(Hash)

  "#{h.fetch('repository')}:#{h.fetch('tag')}"
end

def amqp_url_for_compose(v)
  user = v.dig("rabbitmq", "auth", "username") || "guest"
  pass = v.dig("rabbitmq", "auth", "password") || "guest"
  port = v.dig("rabbitmq", "service", "amqpPort") || 5672
  u = URI.encode_www_form_component(user)
  p = URI.encode_www_form_component(pass)
  "amqp://#{u}:#{p}@rabbitmq:#{port}/"
end

v = YAML.load_file(VALUES_PATH)
obs = v["observability"] || {}

mysql_port = v.dig("mysql", "service", "port") || 3306
rabbit_amqp_port = v.dig("rabbitmq", "service", "amqpPort") || 5672
rabbit_mgmt_port = v.dig("rabbitmq", "service", "managementPort") || 15672
gateway_port = v.dig("apiGateway", "service", "port") || 8000
validation_port = v.dig("validationService", "service", "port") || 8001
exec_port = v.dig("executionService", "service", "port") || 8002
worker_port = v.dig("workerService", "service", "port") || 8003
reporting_port = v.dig("reportingService", "service", "port") || 8004
prometheus_port = obs.dig("prometheus", "service", "port") || 9090
loki_port = obs.dig("loki", "service", "port") || 3100
tempo_port = obs.dig("tempo", "service", "port") || 3200
tempo_otlp_grpc_port = obs.dig("tempo", "service", "otlpGrpcPort") || 4317
tempo_otlp_http_port = obs.dig("tempo", "service", "otlpHttpPort") || 4318
otel_otlp_http_port = obs.dig("otelCollector", "service", "otlpHttpPort") || 4318
otel_health_port = obs.dig("otelCollector", "service", "healthPort") || 13133
otel_metrics_port = obs.dig("otelCollector", "service", "metricsPort") || 8889
grafana_port = obs.dig("grafana", "service", "port") || 3000

lines = []
lines << "# Generated by scripts/gen-compose-env-from-values.rb from charts/cicd/values.yaml"
lines << "# DO NOT EDIT BY HAND — run: ruby scripts/gen-compose-env-from-values.rb"

lines << "MYSQL_ROOT_PASSWORD=#{v.dig('mysql', 'auth', 'rootPassword')}"
lines << "MYSQL_USER=#{v.dig('mysql', 'auth', 'username')}"
lines << "MYSQL_PASSWORD=#{v.dig('mysql', 'auth', 'password')}"
lines << "MYSQL_DATABASE=#{v.dig('mysql', 'auth', 'database')}"
lines << "MYSQL_PORT=#{mysql_port}"

lines << "MYSQL_IMAGE=#{image_string(v.dig('mysql', 'image'))}"
lines << "MIGRATION_IMAGE=#{image_string(v.dig('migration', 'image'))}"

lines << "API_GATEWAY_IMAGE=#{image_string(v.dig('apiGateway', 'image'))}"
lines << "VALIDATION_SERVICE_IMAGE=#{image_string(v.dig('validationService', 'image'))}"
lines << "ORCHESTRATOR_SERVICE_IMAGE=#{image_string(v.dig('executionService', 'image'))}"
lines << "WORKER_SERVICE_IMAGE=#{image_string(v.dig('workerService', 'image'))}"
lines << "REPORTING_SERVICE_IMAGE=#{image_string(v.dig('reportingService', 'image'))}"

lines << "PROMETHEUS_IMAGE=#{image_string(obs.dig('prometheus', 'image'))}"
lines << "LOKI_IMAGE=#{image_string(obs.dig('loki', 'image'))}"
lines << "TEMPO_IMAGE=#{image_string(obs.dig('tempo', 'image'))}"
lines << "OTEL_COLLECTOR_IMAGE=#{image_string(obs.dig('otelCollector', 'image'))}"
lines << "OTEL_COLLECTOR_ENDPOINT=http://otel-collector:#{otel_otlp_http_port}"
lines << "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf"
lines << "PROMETHEUS_PORT=#{prometheus_port}"
lines << "LOKI_PORT=#{loki_port}"
lines << "TEMPO_PORT=#{tempo_port}"
lines << "TEMPO_OTLP_GRPC_PORT=#{tempo_otlp_grpc_port}"
lines << "TEMPO_OTLP_HTTP_PORT=#{tempo_otlp_http_port}"
lines << "OTEL_COLLECTOR_OTLP_HTTP_PORT=#{otel_otlp_http_port}"
lines << "OTEL_COLLECTOR_OTLP_HOST_PORT=4319"
lines << "OTEL_COLLECTOR_HEALTH_PORT=#{otel_health_port}"
lines << "OTEL_COLLECTOR_METRICS_PORT=#{otel_metrics_port}"
lines << "OTEL_COLLECTOR_METRICS_HOST_PORT=8890"
lines << "PROMTAIL_IMAGE=#{image_string(obs.dig('promtail', 'image'))}"
lines << "GRAFANA_IMAGE=#{image_string(obs.dig('grafana', 'image'))}"
lines << "GRAFANA_PORT=#{grafana_port}"

if v.dig("rabbitmq", "image")
  lines << "RABBITMQ_IMAGE=#{image_string(v.dig('rabbitmq', 'image'))}"
else
  # Legacy fallback if rabbitmq.image is absent
  rabbit = v.dig("composeLocal", "rabbitmq", "image") || "rabbitmq:3-management-alpine"
  lines << "RABBITMQ_IMAGE=#{rabbit}"
end

lines << "RABBITMQ_USER=#{v.dig('rabbitmq', 'auth', 'username') || 'guest'}"
lines << "RABBITMQ_PASSWORD=#{v.dig('rabbitmq', 'auth', 'password') || 'guest'}"
lines << "RABBITMQ_URL=#{amqp_url_for_compose(v)}"
lines << "RABBITMQ_AMQP_PORT=#{rabbit_amqp_port}"
lines << "RABBITMQ_MANAGEMENT_PORT=#{rabbit_mgmt_port}"
lines << "API_GATEWAY_PORT=#{gateway_port}"
lines << "VALIDATION_SERVICE_PORT=#{validation_port}"
lines << "ORCHESTRATOR_SERVICE_PORT=#{exec_port}"
lines << "WORKER_SERVICE_PORT=#{worker_port}"
lines << "REPORTING_SERVICE_PORT=#{reporting_port}"
lines << "VALIDATION_URL=http://validation-service:#{validation_port}"
lines << "ORCHESTRATOR_URL=http://orchestrator-service:#{exec_port}"
lines << "WORKER_URL=http://worker-service:#{worker_port}"
lines << "REPORTING_URL=http://reporting-service:#{reporting_port}"
lines << "REPORT_DB_DSN=#{v.dig('mysql', 'auth', 'username')}:#{v.dig('mysql', 'auth', 'password')}@tcp(mysql:#{mysql_port})/#{v.dig('mysql', 'auth', 'database')}?parseTime=true&charset=utf8mb4&loc=UTC"

lines << "PUBLISHER_CONCURRENCY=#{v.dig('executionService', 'publisherConcurrency') || 1}"
lines << "WORKER_CONCURRENCY=#{v.dig('workerService', 'concurrency') || 1}"
lines << "WORKER_JOB_CPU_LIMIT=#{v.dig('workerService', 'jobResources', 'cpuLimit') || ''}"
lines << "WORKER_JOB_NANO_CPUS=#{v.dig('workerService', 'jobResources', 'nanoCPUs') || ''}"
lines << "WORKER_JOB_MEMORY_LIMIT_MB=#{v.dig('workerService', 'jobResources', 'memoryLimitMB') || ''}"

File.write(OUT_PATH, lines.join("\n") + "\n")
puts "Wrote #{OUT_PATH}" if ARGV.empty?
