#!/usr/bin/env ruby
# frozen_string_literal: true

# Reads charts/e-team/values.yaml and writes compose.values.env for Docker Compose.
# Single source of truth with Helm: worker concurrency, RabbitMQ auth/URL, execution URL for worker.
# Run from repo root: ruby scripts/gen-compose-env-from-values.rb

require "uri"
require "yaml"

ROOT = File.expand_path("..", __dir__)
VALUES_PATH = File.join(ROOT, "charts/e-team/values.yaml")
OUT_PATH = ARGV[0] ? File.expand_path(ARGV[0]) : File.join(ROOT, "compose.values.env")

def image_string(h)
  raise ArgumentError, "missing image hash" unless h.is_a?(Hash)

  "#{h.fetch('repository')}:#{h.fetch('tag')}"
end

def amqp_url_for_compose(v)
  user = v.dig("rabbitmq", "auth", "username") || "guest"
  pass = v.dig("rabbitmq", "auth", "password") || "guest"
  port = v.dig("rabbitmq", "service", "amqpPort") || 5672
  u = URI.encode_www_form_component(user)
  p = URI.encode_www_form_component(pass)
  "amqp://#{u}:#{p}@rabbitmq:#{port}/"
end

v = YAML.load_file(VALUES_PATH)
obs = v["observability"] || {}

lines = []
lines << "# Generated by scripts/gen-compose-env-from-values.rb from charts/e-team/values.yaml"
lines << "# DO NOT EDIT BY HAND — run: ruby scripts/gen-compose-env-from-values.rb"

lines << "MYSQL_ROOT_PASSWORD=#{v.dig('mysql', 'auth', 'rootPassword')}"
lines << "MYSQL_USER=#{v.dig('mysql', 'auth', 'username')}"
lines << "MYSQL_PASSWORD=#{v.dig('mysql', 'auth', 'password')}"
lines << "MYSQL_DATABASE=#{v.dig('mysql', 'auth', 'database')}"

lines << "MYSQL_IMAGE=#{image_string(v.dig('mysql', 'image'))}"
lines << "MIGRATION_IMAGE=#{image_string(v.dig('migration', 'image'))}"

lines << "API_GATEWAY_IMAGE=#{image_string(v.dig('apiGateway', 'image'))}"
lines << "VALIDATION_SERVICE_IMAGE=#{image_string(v.dig('validationService', 'image'))}"
lines << "EXECUTION_SERVICE_IMAGE=#{image_string(v.dig('executionService', 'image'))}"
lines << "WORKER_SERVICE_IMAGE=#{image_string(v.dig('workerService', 'image'))}"
lines << "REPORTING_SERVICE_IMAGE=#{image_string(v.dig('reportingService', 'image'))}"

lines << "PROMETHEUS_IMAGE=#{image_string(obs.dig('prometheus', 'image'))}"
lines << "LOKI_IMAGE=#{image_string(obs.dig('loki', 'image'))}"
lines << "TEMPO_IMAGE=#{image_string(obs.dig('tempo', 'image'))}"
lines << "OTEL_COLLECTOR_IMAGE=#{image_string(obs.dig('otelCollector', 'image'))}"
lines << "PROMTAIL_IMAGE=#{image_string(obs.dig('promtail', 'image'))}"
lines << "GRAFANA_IMAGE=#{image_string(obs.dig('grafana', 'image'))}"

if v.dig("rabbitmq", "image")
  lines << "RABBITMQ_IMAGE=#{image_string(v.dig('rabbitmq', 'image'))}"
else
  # Legacy fallback if rabbitmq.image is absent
  rabbit = v.dig("composeLocal", "rabbitmq", "image") || "rabbitmq:3-management-alpine"
  lines << "RABBITMQ_IMAGE=#{rabbit}"
end

lines << "RABBITMQ_USER=#{v.dig('rabbitmq', 'auth', 'username') || 'guest'}"
lines << "RABBITMQ_PASSWORD=#{v.dig('rabbitmq', 'auth', 'password') || 'guest'}"
lines << "RABBITMQ_URL=#{amqp_url_for_compose(v)}"

exec_port = v.dig("executionService", "service", "port") || 8002
lines << "EXECUTION_URL=http://execution-service:#{exec_port}"

lines << "WORKER_CONCURRENCY=#{v.dig('workerService', 'concurrency') || 1}"

File.write(OUT_PATH, lines.join("\n") + "\n")
puts "Wrote #{OUT_PATH}" if ARGV.empty?
